#!/bin/bash
FILE=/etc/crontab
{
	if ls ~/md5sum_hash.txt; then
		if md5sum -c md5sum_hash.txt; then
			:
		else
			mail -s "Warning : /etc/crontab has been modified" rkrief@student.42.fr
			md5sum $FILE > ~/md5sum_hash.txt
		fi
	else
		md5sum $FILE > ~/md5sum_hash.txt;
	fi
} $> /dev/null
